---
  - name: intall resolvconf
    apt: 
      name:
      - resolvconf
      state: present
      update_cache: true

  - name: copy resolve conf file
    copy: src={{ item.src}} dest={{item.dest}}
    with_items:
      - { src: "{{root_dir}}/resolvconf/common-resolve.base", dest: '/etc/resolvconf/resolv.conf.d/base'}
      - { src: "{{root_dir}}/resolvconf/common-resolve.head", dest: '/etc/resolvconf/resolv.conf.d/head'}

  - name: Create a symbolic link /etc/resolv.conf -> /run/resolvconf/resolv.conf
    file:
      src: /run/resolvconf/resolv.conf
      dest: /etc/resolv.conf
      state: link
      force: yes

  - name: reload resolvconf
    shell: /usr/sbin/resolvconf -u