- hosts: wireguard-node
  name: set up wireguard
  become: yes
  become_method: su
  tasks:

      - name: install resolvconf
        apt: 
          name:
          - wireguard
          state: present
          update_cache: true

      - name: copy config files
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/home/honza/Documents/CDNLab/kafka/{{dirName}}/wg0.conf', dest: '/etc/wireguard/wg0.conf'}

      - name: run a wireguard quick-up service
        systemd:
          name: wg-quick@wg0.service
          state: restarted
          enabled: yes
