---
  - name: install wireguard
    apt: 
      name:
      - wireguard
      state: present
      update_cache: true

  - name: copy wg config files
    copy: src={{ item.src}} dest={{item.dest}}
    with_items:
      - { src: "{{root_dir}}/{{instanceName}}/wg0.conf", dest: '/etc/wireguard/wg0.conf'}

  - name: run a wireguard quick-up service
    systemd:
      name: wg-quick@wg0.service
      state: restarted
      enabled: yes
