global:
  scrape_interval: 15s 
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:

  - job_name: "wireguard"
    static_configs:
      - targets: 
        - wg.lab:9586
    metrics_path: /metrics

  - job_name: "nginx"
    static_configs:
      - targets: 
        - nginx-proxy.lab:9113
    metrics_path: /metrics

# not sure if this multiline config is valid
  - job_name: "zookeeper"
    static_configs:
      - targets: 
        - zookeeper1.lab:7000
        - zookeeper2.lab:7000
        - zookeeper3.lab:7000
        - zookeeper4.lab:7000
        - zookeeper5.lab:7000
    metrics_path: /metrics
