---

  - name: Create a symbolic link /etc/resolv.conf -> /run/systemd/resolve/resolv.conf
    file:
      src: /run/systemd/resolve/stub-resolv.conf
      dest: /etc/resolv.conf
      state: link
      force: yes

  - name: enable and restart resolved
    systemd:
      name: systemd-resolved.service
      state: restarted
      enabled: yes


