---
  - name: Include wireguard variables
    include_vars:
      file: "{{root_dir}}/ansible/variables/wireguard.vars"
# There should be better way for handling wireguard intranet vpns. There should be way set up a mechanism of automatic peer handling, so peers are not hard coded.
  - name: install wireguard
    apt: 
      name:
      - wireguard
      state: present
      update_cache: true

  - name: copy wg config file
    copy: 
      src: "{{root_dir}}/wireguard/confs/{{instanceName}}-wg0.conf"
      dest: '/etc/wireguard/wg0.conf'

  - name: Inline endpoint ip
    lineinfile:
      path: /etc/wireguard/wg0.conf
      regexp: '^Endpoint'
      line: "Endpoint = {{wireguardIP}}:55555"

  - name: run a wireguard quick-up service
    systemd:
      name: wg-quick@wg0.service
      state: restarted
      enabled: yes
