---
# I have set up dns to allow not hardocing ip addresses
  - name: set up dns server
    hosts: bind
    become: true
    become_method: su
    tasks:

      - import_tasks: "{{ root_dir }}/ansible/tasks/networkd-task.yml"
      - import_tasks: "{{ root_dir }}/ansible/tasks/resolved-task.yml"
      - import_tasks: "{{ root_dir }}/ansible/tasks/wireguard-task.yml"

      - name: Installs bind
        apt: 
          name:
          - bind9
          state: present
          update_cache: true

      - name: Create zones dir
        file: 
          path: /etc/bind/zones
          state: directory

      - name: Copy bind config files
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: "{{ root_dir }}/bind/named.conf.local", dest: '/etc/bind/named.conf.local'}
          - { src: "{{ root_dir }}/bind/named.conf.options", dest: '/etc/bind/named.conf.options'}
          - { src: "{{ root_dir }}/bind/zones/db.lab", dest: '/etc/bind/zones/db.lab'}

      - name: Restart named for dns record update (its ok, we dont have a secondary)
        systemd:
          name: named.service
          state: restarted
          enabled: yes

      - import_tasks: "{{ root_dir }}/ansible/tasks/reboot-task.yml"
      