---
  - name: set up nginx web server
    hosts: nginx-web
    become: true
    become_method: su
    tasks:

      - import_tasks: "{{ root_dir }}/ansible/tasks/networkd-task.yml"
      - import_tasks: "{{ root_dir }}/ansible/tasks/resolved-task.yml"
      - import_tasks: "{{ root_dir }}/ansible/tasks/wireguard-task.yml"

      - name: Installs nginx
        apt: 
          name:
          - nginx
          state: present
          update_cache: true

      - name: Delate default site
        file: 
          path: /etc/nginx/sites-enabled/default
          state: absent

      - name: Copy website configuration file
        copy:
          src: "{{ root_dir }}/nginx-web/nginx-site-config.nginx"
          dest: '/etc/nginx/sites-enabled/files-serve'

      - name: Create /data/images directory
        file: 
          path: /data/images
          state: directory
          
      - name: Download example images
        get_url:
          url: "{{item}}"
          mode: '0755'
          force: no
          dest: /data/images/
        loop:
        - 'https://cdn.discordapp.com/attachments/716803899931230229/998573689060741120/unknown.png'
        - 'https://cdn.discordapp.com/attachments/716803899931230229/998575534718074981/unknown.gif'

      - name: Reload nginx
        shell: /usr/sbin/nginx -s reload
          
      - import_tasks: "{{ root_dir }}/ansible/tasks/reboot-task.yml"
      