---
  - name: set up kafka server
    hosts: zookeeper
    become: true
    become_method: su
    tasks:
    
      - import_tasks: "{{ root_dir }}/ansible/tasks/networkd-task.yml"
      - import_tasks: "{{ root_dir }}/ansible/tasks/resolved-task.yml"
      - import_tasks: "{{ root_dir }}/ansible/tasks/wireguard-task.yml"
      - import_tasks: "{{ root_dir }}/ansible/tasks/unarchive-zookeeper-task.yml"

      - name: Installing jre 
        apt: 
          name:
          - default-jre
          state: present
          update_cache: true

      - name: Create directory structure for zookeeper
        file:
          path: /data/zookeeper
          state: directory
          recurse: yes

      - name: Creating /data/zookeeper
        file:
          path: /data/zookeeper
          state: directory
          recurse: yes

      - name: Creating a zookeeper ID file
        copy:
          dest: /data/zookeeper/myid
          content: "{{zookeeperID}}"

      - name: Creating a zookeeper config file
        copy:
          dest: /opt/apache-zookeeper-3.8.0-bin/conf/zoo.cfg
          content: |
            tickTime=2000
            dataDir=/data/zookeeper
            clientPort=2181
            maxClientCnxns=60
            initLimit=10
            syncLimit=5
            server.1={{zookeeperIP1}}:2888:3888
            server.2={{zookeeperIP2}}:2888:3888
            server.3={{zookeeperIP3}}:2888:3888
            server.4={{zookeeperIP4}}:2888:3888
            server.5={{zookeeperIP5}}:2888:3888
            metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider

      - name: Copy zookeeper services
        copy: 
          src: "{{ root_dir }}/zookeeper/zookeeper.service"
          dest: '/etc/systemd/system/zookeeper.service'

      - name: Adding user for kafka (for group)
        user:
          name: kafka
          shell: /sbin/nologin

      - name: Adding user for zookeeper
        user:
          name: zookeeper
          append: yes
          groups: kafka
          shell: /sbin/nologin

      - name: Change ownership of zookeeper files
        file:
          path: "{{item}}"
          owner: zookeeper
          group: kafka
          mode: '775'
          recurse: yes
        loop:
          - /opt/kafka_2.13-3.2.0
          - /data/zookeeper

      - name: Enable and restart zookeeper service
        systemd:
          name: zookeeper.service
          state: restarted
          enabled: yes
          daemon_reload: yes
                    
      - import_tasks: "{{ root_dir }}/ansible/tasks/reboot-task.yml"
      