- name: install wireguard dependencies
  hosts: "*"
  tasks:
    - name: install dependencies
      apt: 
        name: resolvconf
        state: present
        update_cache: true
      become: true

  