---
  - name: set up dns server
    hosts: bind
    become: yes
    become_method: su
    tasks:
    
      - import_tasks: "{{ root_dir }}/playbooks/tasks/interfaces-task.yml"
      - import_tasks: "{{ root_dir }}/playbooks/tasks/resolvconf-task.yml"
      - import_tasks: "{{ root_dir }}/playbooks/tasks/wireguard-task.yml"

      - name: installs bind
        apt: 
          name:
          - bind9
          state: present
          update_cache: true

      - name: Create zones dir
        file: 
          path: /etc/bind/zones
          state: directory

      - name: copy resolve conf file
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: "{{ root_dir }}/bind/named.conf.local", dest: '/etc/bind/named.conf.local'}
          - { src: "{{ root_dir }}/bind/named.conf.options", dest: '/etc/bind/zones/named.conf.options'}
          - { src: "{{ root_dir }}/bind/zones/db.lab", dest: '/etc/bind/zones/db.lab'}

      - name: restart named for dns record update (its ok, we dont have secondary)
        command: "{{item}}"
        loop:
          - "systemctl restart named"

    