---
# There could be better naming for Kafka dir...
  - name: set up kafka server
    hosts: kafka
    become: true
    become_method: su
    tasks:
    
      - import_tasks: "{{ root_dir }}/playbooks/tasks/networkd-task.yml"
      - import_tasks: "{{ root_dir }}/playbooks/tasks/resolved-task.yml"
      - import_tasks: "{{ root_dir }}/playbooks/tasks/wireguard-task.yml"
      - import_tasks: "{{ root_dir }}/playbooks/tasks/unarchive-kafka-task.yml"

      - name: Adding user for kafka
        user:
          name: kafka
          shell: /sbin/nologin

      - name: change ownership of kafka files
        file:
          path: /opt/kafka_2.13-3.2.0
          owner: kafka
          group: kafka
          mode: '775'
          recurse: yes

      - name: Inline broker id
        lineinfile:
          path: /opt/kafka_2.13-3.2.0/config/server.properties
          regexp: '^broker.id='
          line: broker.id={{brokerId}}

      - name: Inline zookeeper IP
        lineinfile:
          path: /opt/kafka_2.13-3.2.0/config/server.properties
          regexp: '^zookeeper.connect='
          line: zookeeper.connect={{zookeeperIP}}:2181

      - name: copy kafka service
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: "{{ root_dir }}/kafka/kafka.service", dest: '/etc/systemd/system/kafka.service'}

      - name: enable and restart kafka service
        systemd:
          name: kafka.service
          state: restarted
          enabled: yes
          daemon_reload: yes
