---
  - name: set up nginx web server
    hosts: nginx-web
    become: yes
    become_method: su
    tasks:

      - import_tasks: "{{ root_dir }}/playbooks/tasks/interfaces-task.yml"
      - import_tasks: "{{ root_dir }}/playbooks/tasks/resolvconf-task.yml"
      - import_tasks: "{{ root_dir }}/playbooks/tasks/wireguard-task.yml"

      - name: installs nginx
        apt: 
          name:
          - nginx
          state: present
          update_cache: true

      - name: copy local files serve conf
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: "{{ root_dir }}/nginx-web/nginx-site-config.nginx", dest: '/etc/nginx/sites-enabled/files-serve'}

      - name: restart nginx
        systemd:
          name: nginx.service
          state: restarted
          enabled: yes
