---
  - name: set up nginx proxy server
    hosts: nginx-proxy
    become: yes
    become_method: su
    tasks:
      - name: wireguard, resolvconf, nginx install
        apt: 
          name:
          - wireguard
          - resolvconf
          - nginx
          state: present
          update_cache: true

      - name: copy keys and config files
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/home/honza/Documents/CDNLab/nginx-proxy/wg0.conf', dest: '/etc/wireguard/wg0.conf'}
      
      - name: run a wireguard quick-up service
        systemd:
          name: wg-quick@wg0.service
          state: started
          enabled: yes
      
      - name: copy interfaces
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/home/honza/Documents/CDNLab/interfaces/nginx-proxy-enp1s0', dest: '/etc/network/interfaces.d/enp1s0'}
          - { src: '/home/honza/Documents/CDNLab/interfaces/common-interfaces', dest: '/etc/network/interfaces'}
      
      - name: copy resolve conf file
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/home/honza/Documents/CDNLab/resolvconf/common-resolve', dest: '/etc/resolvconf/resolv.conf.d/base'}

      - name: make /opt/nginx dir
        ansible.builtin.file:
          path: /opt/nginx
          state: directory

      - name: copy nginx exporter
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/home/honza/Documents/CDNLab/nginx-web/nginx-prometheus-exporter', dest: '/opt/nginx/nginx-prom-export'}

      - name: restart nginx
        command: nginx -s reload # errors out, why?

    