---
  - name: set up nginx proxy server
    hosts: nginx-proxy
    become: true
    become_method: su
    tasks:

      - import_tasks: "{{ root_dir }}/playbooks/tasks/interfaces-task.yml"
      - import_tasks: "{{ root_dir }}/playbooks/tasks/resolvconf-task.yml"
      - import_tasks: "{{ root_dir }}/playbooks/tasks/wireguard-task.yml"

      - name: installs nginx
        apt: 
          name:
          - nginx
          state: present
          update_cache: true
          
      - name: copy proxy site conf
        copy:
          src: "{{ root_dir }}/nginx-proxy/nginx-proxy-site.nginx"
          dest: '/etc/nginx/sites-enabled/proxy-site'
 
      - name: Delate default site
        file: 
          path: /etc/nginx/sites-enabled/default
          state: absent

      - name: reload nginx
        shell: /usr/sbin/nginx -s reload
          
      - name: make /opt/nginx dir
        ansible.builtin.file:
          path: /opt/nginx
          state: directory

      - name: Download nginx exporter
        get_url:
          url: 'https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.10.0/nginx-prometheus-exporter_0.10.0_linux_amd64.tar.gz'
          dest: /tmp
          mode: '0755'

      - name: unarchive exporter
        unarchive:
          src: "/tmp/nginx-prometheus-exporter_0.10.0_linux_amd64.tar.gz"
          remote_src: yes
          dest: /opt/nginx

      - name: Adding user for prometheus wg exporter
        user:
          name: wg_exporter
          shell: /sbin/nologin

      - name: change ownership of exporter files
        file:
          path: /opt/nginx
          owner: wg_exporter
          group: wg_exporter
          recurse: yes

      - name: copy exporter service file
        copy: 
          src: "{{ root_dir }}/nginx-proxy/prom-nginx-exporter.service"
          dest: '/etc/systemd/system/prom-nginx-exporter.service'

      - name: run a prometheus exporter for nginx
        systemd:
          name: prom-nginx-exporter.service
          state: restarted
          enabled: yes
          daemon_reload: yes
