---
  - name: set up prometheus server
    hosts: prometheus
    become: yes
    become_method: su
    tasks:

      - import_tasks: "{{ root_dir }}/playbooks/tasks/interfaces-task.yml"
      - import_tasks: "{{ root_dir }}/playbooks/tasks/resolvconf-task.yml"
      - import_tasks: "{{ root_dir }}/playbooks/tasks/wireguard-task.yml"

      - name: Create /opt/prometheus dir
        file: 
          path: /opt/prometheus
          state: directory

      - name: copy systemd service unit file and related files
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: "{{ root_dir }}/prometheus/prometheus.service", dest: '/etc/systemd/system/prometheus.service'}
          - { src: "{{ root_dir }}/prometheus/prometheus-config.yml", dest: '/opt/prometheus/prometheus.yml'}

      - name: Adding user for prometheus
        user:
          name: prometheus
          shell: /sbin/nologin

      - name: enable and restart prometheus service
        systemd:
          name: prometheus.service
          state: restarted
          enabled: yes
          daemon_reload: yes
