---
  - name: install wireguard dependencies
    hosts: wireguard
    tasks:
      - name: wireguard
        apt: 
          name:
          - wireguard
          - resolvconf
          state: present
          update_cache: true
        become: yes
        become_method: su

    