---
  - name: install wireguard dependencies
    hosts: wireguard
    tasks:
      - name: install dependencies
        apt: 
          name: wireguard
          state: present
          update_cache: true
        become: yes
        become_method: su

    