---
  - name: set up wireguard server
    hosts: wireguard
    become: true
    become_method: su
    tasks:
      - import_tasks: "{{ root_dir }}/playbooks/tasks/interfaces-task.yml"
      - import_tasks: "{{ root_dir }}/playbooks/tasks/resolvconf-task.yml"
      - import_tasks: "{{ root_dir }}/playbooks/tasks/wireguard-task.yml"

      - name: installing utils
        apt: 
          name:
          - git
          - curl
          - build-essential
          state: present
          update_cache: true

      - name: copy wg config file
        copy: 
          src: "{{ root_dir }}/wireguard/wg0.conf"
          dest: '/etc/wireguard/wg0.conf'

      - name: run a wireguard quick-up service
        systemd:
          name: wg-quick@wg0.service
          state: restarted
          enabled: yes

      - name: set forwarding to 1
        ansible.posix.sysctl:
          name: net.ipv4.ip_forward
          value: '1'
          sysctl_set: yes
          state: present
          reload: yes

      - name: Download rust installer
        get_url:
          url: https://sh.rustup.rs
          dest: /tmp/sh.rustup.rs
          mode: '0755'
          force: 'yes'

      - name: install rust/cargo
        shell: /tmp/sh.rustup.rs -y

      - name: Get wireguard exporter
        git:
          repo: https://github.com/MindFlavor/prometheus_wireguard_exporter.git
          dest: /opt/prometheus_wireguard_exporter
          single_branch: yes
          version: master

      - name: compile exporter 
        shell: cargo install --path /opt/prometheus_wireguard_exporter

      - name: Adding user for prometheus wg exporter
        user:
          name: wg_exporter
          shell: /sbin/nologin

      - name: change ownership of exporter files
        file:
          path: /opt/prometheus_wireguard_exporter
          owner: wg_exporter
          group: wg_exporter
          recurse: yes

      - name: copy exporter service file
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: "{{ root_dir }}/wireguard/prometheus-wg-exporter.service", dest: '/etc/systemd/system/prom-wg-exporter.service'}

      - name: run a prometheus exporter for wireguard
        systemd:
          name: prom-wg-exporter.service
          state: started
          enabled: yes
          daemon_reload: yes
          
