---
  - name: set up wireguard server
    hosts: wireguard
    become: yes
    become_method: su
    tasks:
      
      - name: copy interfaces
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/home/honza/Documents/CDNLab/interfaces/wg-enp1s0', dest: '/etc/network/interfaces.d/enp1s0'}
          - { src: '/home/honza/Documents/CDNLab/interfaces/common-interfaces', dest: '/etc/network/interfaces'}
      
      - name: wireguard and resolvconf install
        apt: 
          name:
          - wireguard
          - resolvconf
          - git
          - curl
          - build-essential
          state: present
          update_cache: true

      - name: copy keys and config files
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/home/honza/Documents/CDNLab/wireguard/wg0.conf', dest: '/etc/wireguard/wg0.conf'}
          #- { src: './wireguard/private.key', dest: '/etc/wireguar/private.pub'}
          #- { src: './wireguard/public.key', dest: '/etc/wireguar/public.key'}

      - name: run a wireguard quick-up service
        systemd:
          name: wg-quick@wg0.service
          state: restarted
          enabled: yes

      - name: copy resolve conf file
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/home/honza/Documents/CDNLab/resolvconf/common-resolve.base', dest: '/etc/resolvconf/resolv.conf.d/base'}
          - { src: '/home/honza/Documents/CDNLab/resolvconf/common-resolve.head', dest: '/etc/resolvconf/resolv.conf.d/head'}
        notify:
          - Reload resolv.conf

      - ansible.posix.sysctl:
          name: net.ipv4.ip_forward
          value: '1'
          sysctl_set: yes
          state: present
          reload: yes

      - name: run rust instalation script
        script: /home/honza/Documents/CDNLab/wireguard/rustup-init.sh -y

      - name: Get wireguard exporter
        git:
          repo: https://github.com/MindFlavor/prometheus_wireguard_exporter.git
          dest: /opt/prometheus_wireguard_exporter
          single_branch: yes
          version: master

      - name: compile exporter 
        shell: cargo install --path /opt/prometheus_wireguard_exporter

      - name: Adding user for prometheus wg exporter
        user:
          name: wg_exporter
          shell: /sbin/nologin

      - name: change ownership of exporter files
        file:
          path: /opt/prometheus_wireguard_exporter
          owner: wg_exporter
          group: wg_exporter
          recurse: yes

      - name: copy exporter service file
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/home/honza/Documents/CDNLab/wireguard/prometheus-wg-exporter.service', dest: '/etc/systemd/system/prom-wg-exporter.service'}

      - name: run a prometheus exporter for wireguard
        systemd:
          name: prom-wg-exporter.service
          state: started
          enabled: yes
          daemon_reload: yes
