---
  - name: set up wireguard server
    hosts: wireguard
    become: yes
    become_method: su
    tasks:
      - name: wireguard and resolvconf install
        apt: 
          name:
          - wireguard
          - resolvconf
          state: present
          update_cache: true

      - name: copy keys and config files
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/etc/ansible/CDNLab/wireguard/ansible.pub', dest: '/etc/wireguard/ansible.pub'}
          - { src: '/etc/ansible/CDNLab/wireguard/dns.pub', dest: '/etc/wireguard/dns.pub'}
          - { src: '/etc/ansible/CDNLab/wireguard/wg0.conf', dest: '/etc/wireguard/wg0.conf'}
          #- { src: './wireguard/private.key', dest: '/etc/wireguar/private.pub'}
          #- { src: './wireguard/public.key', dest: '/etc/wireguar/public.key'}
      
      - name: set wg-quick service persistent
        command: "{{item}}"
        loop:
          - "systemctl enable wg-quick@wg0.service"
          - "systemctl daemon-reload"
          - "systemctl start wg-quick@wg0"
      
      - name: copy interfaces
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/etc/ansible/CDNLab/interfaces/wg-enp1s0', dest: '/etc/network/interfaces.d/enp1s0'}
          - { src: '/etc/ansible/CDNLab/interfaces/common-interfaces', dest: '/etc/network/interfaces'}
      
      - name: copy resolve conf file
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/etc/ansible/CDNLab/resolvconf/common-resolve', dest: '/etc/resolvconf/resolv.conf.d/base'}
      
      - name: copy sysctl.conf
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/etc/ansible/CDNLab/wireguard/sysctl.conf', dest: '/etc/sysctl.conf'}
    