---
  - name: set up kafka server
    hosts: zookeeper
    become: yes
    become_method: su
    tasks:
      - import_tasks: "{{ root_dir }}/playbooks/tasks/interfaces-task.yml"
      - import_tasks: "{{ root_dir }}/playbooks/tasks/resolvconf-task.yml"
      - import_tasks: "{{ root_dir }}/playbooks/tasks/unarchive-kafka-task.yml"

      - name: copy zookeeper services
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: "{{ root_dir }}/kafka/zookeeper.service", dest: '/etc/systemd/system/zookeeper.service'}

      - name: Adding user for kafka (for group)
        user:
          name: kafka
          shell: /sbin/nologin

      - name: Adding user for zookeeper
        user:
          name: zookeeper
          append: yes
          groups: kafka
          shell: /sbin/nologin

      - name: enable and restart zookeeper service
        systemd:
          name: zookeeper.service
          state: restarted
          enabled: yes
          daemon_reload: yes
          
