---
  - name: set up kafka server
    hosts: zookeeper
    become: yes
    become_method: su
    tasks:

      - name: copy interfaces
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/home/honza/Documents/CDNLab/interfaces/{{dirName}}-enp1s0', dest: '/etc/network/interfaces.d/enp1s0'}
          - { src: '/home/honza/Documents/CDNLab/interfaces/common-interfaces', dest: '/etc/network/interfaces'}
      
      - name: wireguard, resolvconf
        apt: 
          name:
          - wireguard
          - resolvconf
          - default-jdk
          state: present
          update_cache: true

      - name: copy wg config file
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/home/honza/Documents/CDNLab/kafka/{{dirName}}/wg0.conf', dest: '/etc/wireguard/wg0.conf'}
      
      - name: run a wireguard quick-up service
        systemd:
          name: wg-quick@wg0.service
          state: started
          enabled: yes

      - name: copy resolve conf file
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/home/honza/Documents/CDNLab/resolvconf/common-resolve.base', dest: '/etc/resolvconf/resolv.conf.d/base'}
          - { src: '/home/honza/Documents/CDNLab/resolvconf/common-resolve.head', dest: '/etc/resolvconf/resolv.conf.d/head'}
        notify:
          - Reload resolv.conf

      - name: copy kafka binaries
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/home/honza/Documents/CDNLab/kafka/kafka_2.13-3.2.0/', dest: '/opt/kafka'}

      - name: copy zookeeper services
        copy: src={{ item.src}} dest={{item.dest}}
        with_items:
          - { src: '/home/honza/Documents/CDNLab/kafka/zookeeper.service', dest: '/etc/systemd/system/zookeeper.service'}

      - name: Adding user for kafka
        user:
          name: kafka
          shell: /sbin/nologin

      - name: Adding user for zookeeper
        user:
          name: zookeeper
          append: yes
          groups: kafka
          shell: /sbin/nologin

      - name: enable and restart prometheus service
        systemd:
          name: zookeeper.service
          state: restarted
          enabled: yes
          daemon_reload: yes
          
    handlers:
      - name: Reload resolv.conf
        systemd:
          name: resolvconf.service
          state: restarted
          enabled: yes